name: Docker Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: crazy-max/diun

      - run: ls

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        with:
          version: latest

      - name: Cache Buildx
        uses: ./
        with:
          type: buildx
          path: /tmp/.buildx-cache

      - name: Docker Buildx (build)
        run: |
          docker buildx build \
            --cache-from "type=local,src=/tmp/.buildx-cache" \
            --cache-to "type=local,dest=/tmp/.buildx-cache" \
            --platform linux/386 \
            --output "type=image,push=false" \
            --tag crazymax/diun:dev \
            --file ./Dockerfile ./

