name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  #build:
    #runs-on: ubuntu-latest

    #steps:
    #  - uses: actions/checkout@v2
    #  - run: npm install
    #  - run: npm run build
    #  - run: npm test
    #  - run: npm run lint

  test-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache npm
        uses: ./
        with:
          type: npm
          version: v1
      - name: Install dependencies
        run: npm ci

  test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache per run
        uses: ./
        with:
          type: run
          path: ~/.npm
      - name: Install dependencies
        run: npm ci

  test-last:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache by diff
        uses: ./
        with:
          type: last
          path: ~/.npm
      - name: Install dependencies
        run: npm ci

  test-last:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Auto cache
        uses: ./
        with:
          type: auto
      - name: Install dependencies
        run: npm ci
